// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCmroHoOLfpuq0_V202AhIjb4R6G6oD4',
    appId: '1:121637265346:web:08247dfd9d870ea9c4005b',
    messagingSenderId: '121637265346',
    projectId: 'javascript-firebase-proj-359bb',
    authDomain: 'javascript-firebase-proj-359bb.firebaseapp.com',
    storageBucket: 'javascript-firebase-proj-359bb.appspot.com',
    measurementId: 'G-0PTVLL9SYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkiXYTps0YeXUwXQ-76fOjNImy4tH1pw8',
    appId: '1:121637265346:android:018d34cbe1036d12c4005b',
    messagingSenderId: '121637265346',
    projectId: 'javascript-firebase-proj-359bb',
    storageBucket: 'javascript-firebase-proj-359bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqP_84h0G6ZMg6_3iiHXKvhmmvAXMRSm4',
    appId: '1:121637265346:ios:c3806c113a495bb9c4005b',
    messagingSenderId: '121637265346',
    projectId: 'javascript-firebase-proj-359bb',
    storageBucket: 'javascript-firebase-proj-359bb.appspot.com',
    iosClientId: '121637265346-t5m8mki72u05ms83dhdkjgmrl3apesu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqP_84h0G6ZMg6_3iiHXKvhmmvAXMRSm4',
    appId: '1:121637265346:ios:c3806c113a495bb9c4005b',
    messagingSenderId: '121637265346',
    projectId: 'javascript-firebase-proj-359bb',
    storageBucket: 'javascript-firebase-proj-359bb.appspot.com',
    iosClientId: '121637265346-t5m8mki72u05ms83dhdkjgmrl3apesu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkCmroHoOLfpuq0_V202AhIjb4R6G6oD4',
    appId: '1:121637265346:web:62e11337ce763fa3c4005b',
    messagingSenderId: '121637265346',
    projectId: 'javascript-firebase-proj-359bb',
    authDomain: 'javascript-firebase-proj-359bb.firebaseapp.com',
    storageBucket: 'javascript-firebase-proj-359bb.appspot.com',
    measurementId: 'G-QHWD998J0W',
  );
}
